---

- name: Configure repository
  include_tasks: ../../../../tasks/enable_repo.yml

- name: Setup additional yum packages
  yum:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
      - yum-utils
      - centos-release-scl

- name: setup devtoolset-7-gcc
  yum:
    name: devtoolset-7-gcc*
    update_cache: yes
    enablerepo: centos-sclo-rh-testing
    state: present

- name: Percona Platform for PostgreSQL rpm packages for RHEL and additional tools
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - percona-postgresql-client-common
    - percona-postgresql-common
    - percona-postgresql-server-dev-all
    - percona-postgresql12
    - percona-postgresql12-contrib
    - percona-postgresql12-devel
    - percona-postgresql12-libs
    - percona-postgresql12-llvmjit
    - percona-postgresql12-plperl
    - percona-postgresql12-plpython3
    - percona-postgresql12-pltcl
    - percona-postgresql12-server
    - percona-postgresql12-test
    - openssl-devel
    - llvm-toolset-7-clang
    - llvm5.0
    - llvm-toolset-7
    - readline-devel
    - gcc
    - gcc-c++

- name: Initialize Postgres RHEL
  command: /usr/pgsql-12/bin/postgresql-12-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

- name: Enable gcc 7
  shell: echo "source /opt/rh/devtoolset-7/enable" | sudo tee -a /etc/profile;

- name: Set source
  shell: source /opt/rh/devtoolset-7/enable;

- name: Delete old gcc
  shell: rm /usr/bin/gcc

- name: Set symbol link
  shell: ln -s /opt/rh/devtoolset-7/root/usr/bin/gcc /usr/bin/gcc

- shell: gcc --version
  register: gcc

- debug: var=gcc.stdout_lines

- name: Clone pg_stat_monitor sources
  git:
    repo: "{{ repo }}"
    version: "{{ version }}"
    dest: /tmp/pg_stat_monitor
  vars:
    repo: "{{ lookup('env', 'COMPONENT_REPO') }}"
    version: "{{ lookup('env', 'COMPONENT_VERSION') }}"
  become_user: postgres

- name: Build pg_stat_monitor from sources
  make:
    chdir: "/tmp/pg_stat_monitor"
    params:
      USE_PGXS: 1

- name: Install pg_stat_monitor from sources
  make:
    target: install
    chdir: "/tmp/pg_stat_monitor"
    params:
      USE_PGXS: 1


- name: Add extensions to postgresql.conf for RHEL
  lineinfile:
    path: /var/lib/pgsql/12/data/postgresql.conf
    line: shared_preload_libraries = 'pg_stat_monitor'
  when: ansible_os_family == "RedHat"

- name: Restart Postgres RHEL
  service:
    name: postgresql-12
    state: restarted
  register: out

- name: Start Postgres RHEL
  service:
    name: postgresql-12
    state: started
    enabled: yes
