---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove Postgresql deb packages
      apt:
        name: "{{ packages }}"
        state: absent
        update_cache: yes
      vars:
        packages:
          - percona-postgresql-12
          - percona-postgresql-client-12
          - percona-postgresql-doc-12
          - percona-postgresql-plperl-12
          - percona-postgresql-plpython3-12
          - percona-postgresql-pltcl-12
          - percona-postgresql-server-dev-12
          - percona-postgresql-12-dbgsym
          - percona-postgresql-client-12-dbgsym
          - percona-postgresql-plperl-12-dbgsym
          - percona-postgresql-plpython3-12-dbgsym
          - percona-postgresql-pltcl-12-dbgsym
      when: ansible_os_family == "Debian"

    - name: Remove Percona Platform for PostgreSQL deb packages
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
        - percona-postgresql-plpython-12
        - percona-postgresql-plpython-12-dbgsym
        - percona-postgresql-server-dev-12-dbgsym
      when:
        - ansible_os_family == "Debian"
        - lookup('env', 'PG_VERSION') == "ppg-12.5"

    - name: remove Postgresql rpm packages
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-postgresql12
          - percona-postgresql12
          - percona-postgresql12-contrib
          - percona-postgresql12-debuginfo
          - percona-postgresql12-devel
          - percona-postgresql12-docs
          - percona-postgresql12-libs
          - percona-postgresql12-llvmjit
          - percona-postgresql12-plperl
          - percona-postgresql12-plpython
          - percona-postgresql12-pltcl
          - percona-postgresql12-server
          - percona-postgresql12-test
          - percona-postgresql12-debuginfo
          - percona-postgresql12-debugsource
          - percona-postgresql12-devel-debuginfo
          - percona-postgresql12-libs-debuginfo
          - percona-postgresql12-plperl-debuginfo
          - percona-postgresql12-plpython-debuginfo
          - percona-postgresql12-plpython3-debuginfo
          - percona-postgresql12-pltcl-debuginfo
          - percona-postgresql12-server-debuginfo
      when: ansible_os_family == "RedHat"

    - name: remove pgaudit deb packages
      apt:
        name: percona-postgresql-12-pgaudit
        state: absent
      when: ansible_os_family == "Debian"

    - name: remove pg_repack deb packages
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-postgresql-12-repack
          - percona-postgresql-12-repack-dbgsym
      when: ansible_os_family == "Debian"

    - name: remove pg_repack rpm packages
      yum:
        name: percona-pg_repack12
        state: absent
      when: ansible_os_family == "RedHat"
