
  - name: Set Facts.
    set_fact:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"
      cacheable: true

  - debug:
      msg: "Value of PERCONA_TELEMETRY_URL is : {{ PERCONA_TELEMETRY_URL }}"

  - name: setup epel release
    yum:
      name: epel-release
      update_cache: yes
      state: present
    when: ansible_os_family == "RedHat"

  - name: Clean dnf RHEL8
    become: true
    command: dnf clean all -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Clean dnf oracle linux
    become: true
    command: dnf clean all -y
    when: ansible_os_family == "RedHat" and
      (ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9")

  - name: Enable powertools on oracle linux 8
    become: true
    command: dnf config-manager --set-enabled ol8_codeready_builder
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Enable powertools on oracle linux 9
    become: true
    command: dnf config-manager --set-enabled ol9_codeready_builder
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "9"

  - name: Disable dnf module for RHEL8
    become: true
    command: dnf module disable postgresql -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Disable llvm-toolset dnf module for RHEL8
    become: true
    command: dnf module disable llvm-toolset -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: install Percona Platform for PostgreSQL deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-postgresql
      - percona-postgresql-14
      - percona-postgresql-all
      - percona-postgresql-client
      - percona-postgresql-client-14
      - percona-postgresql-common
      - percona-postgresql-contrib
      - percona-postgresql-doc
      - percona-postgresql-doc-14
      - percona-postgresql-plperl-14
      - percona-postgresql-plpython3-14
      - percona-postgresql-pltcl-14
      - percona-postgresql-server-dev-14
      - percona-postgresql-server-dev-all
      - percona-postgresql-14-dbgsym
      - percona-postgresql-client-14-dbgsym
      - percona-postgresql-plperl-14-dbgsym
      - percona-postgresql-plpython3-14-dbgsym
      - percona-postgresql-pltcl-14-dbgsym
      - postgresql-client-common
      - postgresql-common
    when: ansible_os_family == "Debian"
    environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

  - name: install Percona Platform for PostgreSQL rpm packages for RHEL
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - percona-postgresql-client-common
      - percona-postgresql-common
      - percona-postgresql-server-dev-all
      - percona-postgresql14
      - percona-postgresql14-contrib
      - percona-postgresql14-debuginfo
      - percona-postgresql14-devel
      - percona-postgresql14-docs
      - percona-postgresql14-libs
      - percona-postgresql14-llvmjit
      - percona-postgresql14-plperl
      - percona-postgresql14-plpython3
      - percona-postgresql14-pltcl
      - percona-postgresql14-server
      - percona-postgresql14-test
      - percona-postgresql14-debuginfo
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
    environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

  - name: install Percona Platform for PostgreSQL rpm packages for RHEL
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
        - percona-postgresql-client-common
        - percona-postgresql-common
        - percona-postgresql-server-dev-all
        - percona-postgresql14
        - percona-postgresql14-contrib
        - percona-postgresql14-debuginfo
        - percona-postgresql14-devel
        - percona-postgresql14-docs
        - percona-postgresql14-libs
        - percona-postgresql14-llvmjit
        - percona-postgresql14-plpython3
        - percona-postgresql14-plperl
        - percona-postgresql14-pltcl
        - percona-postgresql14-server
        - percona-postgresql14-test
        - percona-postgresql14-contrib-debuginfo
        - percona-postgresql14-debuginfo
        - percona-postgresql14-debugsource
        - percona-postgresql14-devel-debuginfo
        - percona-postgresql14-libs-debuginfo
        - percona-postgresql14-plperl-debuginfo
        - percona-postgresql14-pltcl-debuginfo
        - percona-postgresql14-plpython3-debuginfo
        - percona-postgresql14-server-debuginfo
        - percona-postgresql14-test-debuginfo
    when: ansible_os_family == "RedHat" and
      (ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9")
    environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

  - name: Check if Telemetry file exisits
    stat:
        path: /usr/local/percona/telemetry_uuid
    register: telemetry_file_check

  - name: Register output of /usr/local/percona/telemetry_uuid
    become: true
    command: cat /usr/local/percona/telemetry_uuid
    register: telemetry_file_output
    when: telemetry_file_check.stat.exists

  - debug:
      msg: "Telemetry file output is : {{ telemetry_file_output }}"
    when: telemetry_file_check.stat.exists
