  - debug:
      msg: "{{ hostvars[inventory_hostname].ansible_os_family }}"
  - debug:
      msg: "{{ hostvars[inventory_hostname].ansible_distribution }}"
  - debug:
      msg: "{{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
  - debug:
      msg: "{{ hostvars[inventory_hostname].ansible_distribution_version }}"
  - name: Clean dnf RHEL8
    become: true
    command: dnf clean all -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Disable dnf module for RHEL8
    become: true
    command: dnf module disable postgresql -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Disable llvm-toolset dnf module for RHEL8
    become: true
    command: dnf module disable llvm-toolset -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: install Percona Platform for PostgreSQL deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-postgresql
      - percona-postgresql-14
      - percona-postgresql-all
      - percona-postgresql-client
      - percona-postgresql-client-14
      - percona-postgresql-client-common
      - percona-postgresql-common
      - percona-postgresql-contrib
      - percona-postgresql-doc
      - percona-postgresql-doc-14
      - percona-postgresql-plperl-14
      - percona-postgresql-plpython3-14
      - percona-postgresql-pltcl-14
      - percona-postgresql-server-dev-14
      - percona-postgresql-server-dev-all
      - percona-postgresql-14-dbgsym
      - percona-postgresql-client-14-dbgsym
      - percona-postgresql-plperl-14-dbgsym
      - percona-postgresql-plpython3-14-dbgsym
      - percona-postgresql-pltcl-14-dbgsym
    when: ansible_os_family == "Debian"

  - name: install Percona Platform for PostgreSQL deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-postgresql-plpython3-14
      - percona-postgresql-plpython3-14-dbgsym
    when:
      - ansible_os_family == "Debian"

  - name: install Percona Platform for PostgreSQL rpm packages for RHEL
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - percona-postgresql-client-common
      - percona-postgresql-common
      - percona-postgresql-server-dev-all
      - percona-postgresql14
      - percona-postgresql14-contrib
      - percona-postgresql14-debuginfo
      - percona-postgresql14-devel
      - percona-postgresql14-docs
      - percona-postgresql14-libs
      - percona-postgresql14-llvmjit
      - percona-postgresql14-plperl
      - percona-postgresql14-plpython3
      - percona-postgresql14-pltcl
      - percona-postgresql14-server
      - percona-postgresql14-test
      - percona-postgresql14-debuginfo
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: install Percona Platform for PostgreSQL rpm packages for RHEL
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
        - percona-postgresql-client-common
        - percona-postgresql-common
        - percona-postgresql-server-dev-all
        - percona-postgresql14
        - percona-postgresql14-contrib
        - percona-postgresql14-debuginfo
        - percona-postgresql14-devel
        - percona-postgresql14-docs
        - percona-postgresql14-libs
        - percona-postgresql14-llvmjit
        - percona-postgresql14-plpython3
        - percona-postgresql14-plperl
        - percona-postgresql14-pltcl
        - percona-postgresql14-server
        - percona-postgresql14-test
        - percona-postgresql14-contrib-debuginfo
        - percona-postgresql14-debuginfo
        - percona-postgresql14-debugsource
        - percona-postgresql14-devel-debuginfo
        - percona-postgresql14-libs-debuginfo
        - percona-postgresql14-plperl-debuginfo
        - percona-postgresql14-pltcl-debuginfo
        - percona-postgresql14-plpython3-debuginfo
        - percona-postgresql14-server-debuginfo
        - percona-postgresql14-test-debuginfo
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"
