
  - name: Set Facts.
    set_fact:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"
      cacheable: true

  - debug:
      msg: "Value of PERCONA_TELEMETRY_URL is : {{ PERCONA_TELEMETRY_URL }}"

  - name: setup epel release
    yum:
      name: epel-release
      update_cache: yes
      state: present
    when: ansible_os_family == "RedHat"

  - name: Clean dnf oracle linux
    become: true
    command: dnf clean all -y
    when: ansible_os_family == "RedHat" and
      (ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9")

  - name: Enable powertools on oracle linux 8
    become: true
    command: dnf config-manager --set-enabled ol8_codeready_builder
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Enable powertools on oracle linux 9
    become: true
    command: dnf config-manager --set-enabled ol9_codeready_builder
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "9"

  - name: Disable dnf postgresql for RHEL8
    become: true
    command: dnf module disable postgresql -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Disable llvm-toolset dnf module for RHEL8
    become: true
    command: dnf module disable llvm-toolset -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: install Percona Platform for PostgreSQL deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-postgresql
      - percona-postgresql-16
      - percona-postgresql-all
      - percona-postgresql-client
      - percona-postgresql-client-16
      - percona-postgresql-common
      - percona-postgresql-contrib
      - percona-postgresql-doc
      - percona-postgresql-doc-16
      - percona-postgresql-plperl-16
      - percona-postgresql-plpython3-16
      - percona-postgresql-pltcl-16
      - percona-postgresql-server-dev-16
      - percona-postgresql-server-dev-all
      - percona-postgresql-16-dbgsym
      - percona-postgresql-client-16-dbgsym
      - percona-postgresql-plperl-16-dbgsym
      - percona-postgresql-plpython3-16-dbgsym
      - percona-postgresql-pltcl-16-dbgsym
      - postgresql-client-common
      - postgresql-common
    when: ansible_os_family == "Debian"
    environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

  - name: install Percona Platform for PostgreSQL deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-postgresql-plpython3-16
      - percona-postgresql-plpython3-16-dbgsym
    when:
      - ansible_os_family == "Debian"

  - name: install Percona Platform for PostgreSQL rpm packages for RHEL
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - percona-postgresql-client-common
      - percona-postgresql-common
      - percona-postgresql-server-dev-all
      - percona-postgresql16
      - percona-postgresql16-contrib
      - percona-postgresql16-debuginfo
      - percona-postgresql16-devel
      - percona-postgresql16-docs
      - percona-postgresql16-libs
      - percona-postgresql16-llvmjit
      - percona-postgresql16-plperl
      - percona-postgresql16-plpython3
      - percona-postgresql16-pltcl
      - percona-postgresql16-server
      - percona-postgresql16-test
      - percona-postgresql16-debuginfo
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
    environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

  - name: install Percona Platform for PostgreSQL rpm packages for RHEL
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
        - percona-postgresql-client-common
        - percona-postgresql-common
        - percona-postgresql-server-dev-all
        - percona-postgresql16
        - percona-postgresql16-contrib
        - percona-postgresql16-debuginfo
        - percona-postgresql16-devel
        - percona-postgresql16-docs
        - percona-postgresql16-libs
        - percona-postgresql16-llvmjit
        - percona-postgresql16-plpython3
        - percona-postgresql16-plperl
        - percona-postgresql16-pltcl
        - percona-postgresql16-server
        - percona-postgresql16-test
        - percona-postgresql16-contrib-debuginfo
        - percona-postgresql16-debuginfo
        - percona-postgresql16-debugsource
        - percona-postgresql16-devel-debuginfo
        - percona-postgresql16-libs-debuginfo
        - percona-postgresql16-plperl-debuginfo
        - percona-postgresql16-pltcl-debuginfo
        - percona-postgresql16-plpython3-debuginfo
        - percona-postgresql16-server-debuginfo
    when: ansible_os_family == "RedHat" and
      (ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9")
    environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

  - name: Check if Telemetry file exisits
    stat:
        path: /usr/local/percona/telemetry_uuid
    register: telemetry_file_check

  - name: Register output of /usr/local/percona/telemetry_uuid
    become: true
    command: cat /usr/local/percona/telemetry_uuid
    register: telemetry_file_output
    when: telemetry_file_check.stat.exists

  - debug:
      msg: "Telemetry file output is : {{ telemetry_file_output }}"
    when: telemetry_file_check.stat.exists
