---

- name: Configure repository
  include_tasks: ../../../../tasks/enable_repo.yml

- name: install additional packages for running tests with apt
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - libipc-run-perl
    - libtext-csv-xs-perl
  retries: 60
  delay: 10
  register: result
  until: result is not failed

- name: install Percona Platform for PostgreSQL Deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - percona-postgresql
    - percona-postgresql-15
    - percona-postgresql-all
    - percona-postgresql-client
    - percona-postgresql-client-15
    - percona-postgresql-client-common
    - percona-postgresql-common
    - percona-postgresql-contrib
    - percona-postgresql-plperl-15
    - percona-postgresql-plpython3-15
    - percona-postgresql-pltcl-15
    - percona-postgresql-server-dev-15
    - percona-postgresql-server-dev-all

- name: Install pgbadger Debian
  apt:
    name: percona-pgbadger
    state: latest
    update_cache: yes

- name: Add user postgres to sudoers
  user:
    name: postgres
    groups: sudo
    append: yes

- name: Clone pgbadger sources
  git:
    repo: "{{ repo }}"
    version: "{{ version }}"
    dest: /tmp/pgbadger
  vars:
    repo: "{{ lookup('env', 'COMPONENT_REPO') }}"
    version: "{{ lookup('env', 'COMPONENT_VERSION') }}"
  become_user: postgres

- name: Make perl for pgbadger
  shell: perl Makefile.PL
  args:
    chdir: /tmp/pgbadger
  become_user: postgres

- name: Build pgbadger from sources
  make:
    chdir: "/tmp/pgbadger"
  become_user: postgres

- name: Install pgbadger from sources
  make:
    target: install
    chdir: "/tmp/pgbadger"
  become: true

- name: Restart Postgres RHEL
  service:
    name: postgresql
    state: restarted
  register: out
