---
- name: Configure repository
  include_tasks: ../../../tasks/install_percona_release.yml

- name: Setting facts so that they will be persisted in the fact cache
  ansible.builtin.set_fact:
    pg_version_to_install: "{{ lookup('env', 'FROM_VERSION') | replace('ppg-','') }}"

- name: End play on oracle linux 9
  meta: end_play
  when: ansible_os_family == "RedHat" and
   ansible_distribution_major_version == "9" and
   pg_version_to_install | string is version('15.1', '<=', strict=True)

- name: End play on Debian 12
  meta: end_play
  when: ansible_os_family == "Debian" and
   ansible_distribution_major_version == "12" and
   pg_version_to_install | string is version('15.3', '<=', strict=True)

- name: End play on Ubuntu 24
  meta: end_play
  when: ansible_distribution == "Ubuntu" and
   ansible_distribution_major_version == "24" and
   pg_version_to_install | string is version('15.6', '<=', strict=True)

- name: Setup initial (old) repository
  command: percona-release enable {{ pg_version }} {{ repo }}
  vars:
    repo: "{{ lookup('env', 'FROM_REPO') }}"
    pg_version: "{{ lookup('env', 'FROM_VERSION') }}"

- name: install Percona Platform for PostgreSQL 15 packages
  include_tasks: ../../../../tasks/install_ppg15.yml

- name: Initialize Postgres RHEL
  command: /usr/pgsql-15/bin/postgresql-15-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "RedHat"

- name: Install PPG tools
  include_tasks: ../../../../tasks/install_ppg15_tools.yml

- name: Start Postgres RHEL
  service:
    name: postgresql-15
    state: started
    enabled: true
  when: ansible_os_family == "RedHat"

- name: Start postgresql service for Debian based
  service:
    name: postgresql
    state: started
    enabled: true
  when: ansible_os_family == "Debian"

- name: Disable old repository
  command: percona-release disable {{ pg_version }} {{ repo }}
  vars:
    repo: "{{ lookup('env', 'FROM_REPO') }}"
    pg_version: "{{ lookup('env', 'FROM_VERSION') }}"

- name: Setup new repository
  command: percona-release enable {{ pg_version }} {{ repo }}
  vars:
    repo: "{{ lookup('env', 'TO_REPO') }}"
    pg_version: "{{ lookup('env', 'VERSION') }}"

- name: install Percona Platform for PostgreSQL deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
      - percona-postgresql
      - percona-postgresql-15
      - percona-postgresql-all
      - percona-postgresql-client
      - percona-postgresql-client-15
      - percona-postgresql-common
      - percona-postgresql-contrib
      - percona-postgresql-doc
      - percona-postgresql-doc-15
      - percona-postgresql-plperl-15
      - percona-postgresql-plpython3-15
      - percona-postgresql-pltcl-15
      - percona-postgresql-server-dev-15
      - percona-postgresql-server-dev-all
      - percona-postgresql-15-dbgsym
      - percona-postgresql-client-15-dbgsym
      - percona-postgresql-plperl-15-dbgsym
      - percona-postgresql-plpython3-15-dbgsym
      - percona-postgresql-pltcl-15-dbgsym
      - postgresql-client-common
      - postgresql-common
  when: ansible_os_family == "Debian"
  environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

- name: install Percona Platform for PostgreSQL deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - percona-postgresql-plpython3-15
    - percona-postgresql-plpython3-15-dbgsym
  when:
    - ansible_os_family == "Debian"

- name: install Percona Platform for PostgreSQL rpm packages for RHEL
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - percona-postgresql-client-common
      - percona-postgresql-common
      - percona-postgresql-server-dev-all
      - percona-postgresql15
      - percona-postgresql15-contrib
      - percona-postgresql15-debuginfo
      - percona-postgresql15-devel
      - percona-postgresql15-docs
      - percona-postgresql15-libs
      - percona-postgresql15-llvmjit
      - percona-postgresql15-plperl
      - percona-postgresql15-plpython3
      - percona-postgresql15-pltcl
      - percona-postgresql15-server
      - percona-postgresql15-test
      - percona-postgresql15-debuginfo
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

- name: install Percona Platform for PostgreSQL rpm packages for RHEL
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
        - percona-postgresql-client-common
        - percona-postgresql-common
        - percona-postgresql-server-dev-all
        - percona-postgresql15
        - percona-postgresql15-contrib
        - percona-postgresql15-debuginfo
        - percona-postgresql15-devel
        - percona-postgresql15-docs
        - percona-postgresql15-libs
        - percona-postgresql15-llvmjit
        - percona-postgresql15-plpython3
        - percona-postgresql15-plperl
        - percona-postgresql15-pltcl
        - percona-postgresql15-server
        - percona-postgresql15-test
        - percona-postgresql15-contrib-debuginfo
        - percona-postgresql15-debuginfo
        - percona-postgresql15-debugsource
        - percona-postgresql15-devel-debuginfo
        - percona-postgresql15-libs-debuginfo
        - percona-postgresql15-plperl-debuginfo
        - percona-postgresql15-pltcl-debuginfo
        - percona-postgresql15-plpython3-debuginfo
        - percona-postgresql15-server-debuginfo
  when: ansible_os_family == "RedHat" and
      (ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9")
  environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

- name: Stop postgresql service for RHEL based
  service:
    name: postgresql-15
    state: stopped
  when: ansible_os_family == "RedHat"

- name: Stop postgresql service for Debian based
  service:
    name: postgresql
    state: stopped
  when: ansible_os_family == "Debian"

- pause:
    minutes: 1

- name: Start postgresql service for RHEL based
  service:
    name: postgresql-15
    state: started
    enabled: true
  when: ansible_os_family == "RedHat"

- name: Start postgresql service for Debian based
  service:
    name: postgresql
    state: started
    enabled: true
  when: ansible_os_family == "Debian"

- name: Display ppg version
  become_user: postgres
  shell: psql -c "select version()"
  register: results

- debug:
      var: results.stdout
