---
- name: Run pg_repack tests
  hosts: all
  become: true
  become_method: sudo
  become_user: postgres
  gather_facts: true
  tasks:
    - name: Create dir for test tablespace
      file:
        path: /var/lib/postgresql/testts
        state: directory

    - name: Create tablespace
      shell: psql -c "create tablespace testts location '/var/lib/postgresql/testts'"

#    - name: Create tablespace
#      postgresql_query:
#        query: create tablespace testts location '/var/lib/postgresql/testts'
    - name: Test pg_repack
      make:
        target: installcheck
        chdir: "/tmp/pg_repack"
        params:
          USE_PGXS: 1
      register: installcheck

    - debug: var=installcheck.stdout_lines
