---

- name: Configure repository
  include_tasks: ../../../../tasks/enable_repo.yml

- name: Setup additional yum packages
  yum:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
      - yum-utils
      - centos-release-scl

- name: setup devtoolset-7-gcc
  yum:
    name: devtoolset-7-gcc*
    update_cache: yes
    enablerepo: centos-sclo-rh-testing
    state: present

- name: Percona Platform for PostgreSQL rpm packages for RHEL and additional tools
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - percona-postgresql-client-common
    - percona-postgresql-common
    - percona-postgresql-server-dev-all
    - percona-postgresql14
    - percona-postgresql14-contrib
    - percona-postgresql14-devel
    - percona-postgresql14-libs
    - percona-postgresql14-llvmjit
    - percona-postgresql14-plperl
    - percona-postgresql14-plpython3
    - percona-postgresql14-pltcl
    - percona-postgresql14-server
    - percona-postgresql14-test
    - openssl-devel
    - llvm-toolset-7-clang
    - llvm5.0
    - llvm-toolset-7
    - readline-devel
    - gcc
    - gcc-c++
    - libevent-devel
    - pandoc
    - libtool
    - openssl
    - pkgconfig

- name: add user to sudo group
  shell: usermod -aG wheel postgres
  args:
    executable: /bin/bash

- shell: gcc --version
  register: gcc

- debug: var=gcc.stdout_lines

- name: Enable gcc 7
  shell: echo "source /opt/rh/devtoolset-7/enable" | sudo tee -a /etc/profile;

- name: Set source
  shell: source /opt/rh/devtoolset-7/enable;

- name: Delete old gcc
  shell: rm /usr/bin/gcc

- name: Set symbol link
  shell: ln -s /opt/rh/devtoolset-7/root/usr/bin/gcc /usr/bin/gcc

- shell: gcc --version
  register: gcc

- debug: var=gcc.stdout_lines

- name: Clone pgbouncer sources
  git:
    repo: "{{ repo }}"
    version: "{{ version }}"
    dest: /var/lib/pgsql/pgbouncer
    recursive: yes
    update: yes
  vars:
    repo: "{{ lookup('env', 'COMPONENT_REPO') }}"
    version: "{{ lookup('env', 'COMPONENT_VERSION') }}"
  become_user: postgres

- name: Autogen pgbouncer
  shell: ./autogen.sh
  args:
    chdir: /var/lib/pgsql/pgbouncer
  become_user: postgres

- name: Configure pgbouncer
  shell: ./configure --prefix=/usr/local
  args:
    chdir: /tmp/pgbouncer
  become_user: postgres
