---
- name: Install vanila postgresql
  include_tasks: ../../../../tasks/install_pg12.yml


- name: Configure repository
  include_tasks: ../../../../tasks/enable_repo.yml

- name: Initialize Postgres RHEL
  command: /usr/pgsql-12/bin/postgresql-12-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "RedHat"

- name: Start Postgres RHEL
  service:
    name: postgresql-12
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Install ppg12 tools
  include_tasks: ../../../../tasks/install_ppg12_tools.yml
