---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: ujammy-${BUILD_NUMBER}-${JOB_NAME}
    region: eu-central-1
    image: ami-0a87a69d69fa289be
    vpc_subnet_id: subnet-0fad4db6fdd8025b6
    instance_type: t2.medium
    ssh_user: ubuntu
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-pg-worker
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../../../../playbooks/create.yml
    destroy: ../../../../playbooks/destroy.yml
    prepare: ../../../../playbooks/prepare.yml
    converge: ../../playbooks/playbook.yml
verifier:
  name: ansible
scenario:
  destroy_sequence:
    - destroy
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - destroy
